title: "YEET Artistic Community Platform"
description: "Revolutionary artistic community platform by Yethikrishna R"
url: "https://yethikrishna.github.io"
baseurl: "/yeet-artistic-platform"

# Build settings
markdown: kramdown
theme: minima

# Exclude files that might cause build issues
exclude:
  - node_modules/
  - yeet_project/
  - docs/
  - "*.zip"
  - "*.py"
  - ".git/"
  - ".github/"
  - vendor/
  - Gemfile*
  - README.md
